### ISSUE TITLE
Cannot generate EF migration in UWP when using Win2D

### ISSUE THREAD

**Issue by geoffmmorgan** [Microsoft/Win2D#290]
I have a UWP project that uses Win2D. When I attempt to generate a migration with EF the migration will fail with the following error.

> System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at Microsoft.Data.Entity.Design.Internal.StartupInvoker..ctor(String startupAssemblyName, String environment)
   at Microsoft.Data.Entity.Design.DbContextOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupAssemblyName, String environment)
   at Microsoft.Data.Entity.Design.MigrationsOperations..ctor(ILoggerProvider loggerProvider, String assemblyName, String startupAssemblyName, String environment, String projectDir, String rootNamespace)
   at Microsoft.Data.Entity.Design.OperationExecutor.<>c__DisplayClass3_0.<.ctor>b__3()
   at Microsoft.Data.Entity.Internal.LazyRef`1.get_Value()
   at Microsoft.Data.Entity.Design.OperationExecutor.<AddMigrationImpl>d__7.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.<>c__DisplayClass4_0`1.<Execute>b__0()
   at Microsoft.Data.Entity.Design.OperationExecutor.OperationBase.Execute(Action action)
Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.

This is due to the use of CanvasBitmap.LoadAsync() from Win2D. Any use of that method will prevent migrations from being generated. I have created a sample project demoing this. You can [find it here](https://github.com/geoffmmorgan/MigrationTest/tree/master)

**Comment by geoffmmorgan** [comment]
I have posted this on the EF core GitHub as well https://github.com/aspnet/EntityFramework/issues/4683

**Comment by shawnhar** [comment]
This looks like an EntityFramework rather than Win2D issue.  Seems the EF bug is understood and getting good traction, so I'm going to close this on the Win2D side.

Thanks for the report!
