### ISSUE TITLE
How to use in a Console app with net5.0-windows10.0.19041.0

### ISSUE THREAD

**Issue by jdluzen** [microsoft/Win2D#822]
I'm attempting to use Win2D because I need something that implements `IDirect3DSurface` so that I can process video frames written to it. (Related question here https://stackoverflow.com/questions/67011957/how-to-get-decoded-video-frames-using-winrt-in-net5)

I've tried to use the following which is directly taken from a test in this repo:
```
            var device = new CanvasDevice();
            var rt = new CanvasRenderTarget(device, 16, 16, 96);
```
But I get the following exception: `Specified cast is not valid.`
```
   at System.Runtime.InteropServices.Marshal.ThrowExceptionForHR(Int32 errorCode)
   at WinRT.IObjectReference.As[T](Guid iid)
   at WinRT.IObjectReference.As(Guid iid)
   at Microsoft.UI.Xaml.DependencyObject..ctor(IObjectReference objRef)
   at Microsoft.Graphics.Canvas.CanvasBitmap..ctor(IObjectReference objRef)
   at Microsoft.Graphics.Canvas.CanvasRenderTarget..ctor(IObjectReference objRef)
   at Microsoft.Graphics.Canvas.CanvasRenderTarget..ctor(ICanvasResourceCreator resourceCreator, Single width, Single height, Single dpi)
   at <my app>.FrameAvailable(MediaPlayer sender, Object args) in <my console app>\WmfFrameSource.cs:line 87
```
#813 is likely related.
I have tried https://github.com/microsoft/Win2D/issues/707#issuecomment-740361674, Microsoft.Graphics.Win2D, and https://github.com/microsoft/Win2D/issues/735#issuecomment-562720179.

**Comment by getrou** [comment]
I believe it is an issue with cswinrt that prevents CanvasBitmap and CanvasRenderTarget from working in net5.0 right now.
The issue tracking this is here: https://github.com/microsoft/CsWinRT/issues/779

Once this issue is fixed CanvasBitmap and CanvasRenderTarget should start working.

**Comment by Extrimis** [comment]
Is this issue fixed or still there, currently i was using win2d for WinUI but it also does not support anything related to CanvasGraphicsDevice
