### ISSUE TITLE
Class not registered?

### ISSUE THREAD

**Issue by suprak** [Microsoft/Win2D#84]
I added installed the Win2D nuget package into my Windows Phone 8.1 project (not Silverlight) however when I try to run and use the library I get an error like this.

How do I trouble shoot this?

[5/22/2015 3:27:45 PM] An exception occurred at: 
System.TypeLoadException: Requested Windows Runtime type 'Microsoft.Graphics.Canvas.CanvasBitmap' is not registered. ---> System.Runtime.InteropServices.COMException: Class not registered (Exception from HRESULT: 0x80040154 (REGDB_E_CLASSNOTREG))
   --- End of inner exception stack trace ---
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at Microsoft.Graphics.Canvas.CanvasBitmap.LoadAsync(ICanvasResourceCreator resourceCreator, IRandomAccessStream stream)
   at K.A.Phone.BlurredBackgroundImage.ImageResources.<LoadAsync>d__6.MoveNext()
A first chance exception of type 'System.TypeLoadException' occurred

**Comment by damyanp** [comment]
Is this the same as issue #59?

**Comment by suprak** [comment]
Installed VS 2015 Update 5 RC and re-installed Win2D and the problem went away.
Thank you!
